[build]
target = "avr-atmega1284p.json"

#https://doc.rust-lang.org/cargo/reference/unstable.html
[unstable]
build-std = ["core"]

# Cargo versions before 2021-02-23 won't recognize this: https://github.com/rust-lang/cargo/pull/9175
[env]
AVR_CPU_FREQUENCY_HZ = "20_000_000"

#[target.'cfg(target_arch = "avr")']
#runner = "ravedude uno --open-console --baudrate 57600"