name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gcc-avr
      run: sudo apt -y install binutils gcc-avr avr-libc
    - name: Build
      run: cargo build --verbose    
